terrarium_lxd_snap_channel: latest/stable
terrarium_lxd_auth_group: terrarium-management
terrarium_lxd_oidc_groups_claim: groups
terrarium_lxd_idp_group_state_path: "{{ terrarium_state_dir }}/lxd-idp-admin-group"
