terrarium_zitadel_enabled: "{{ terrarium_idp_mode == 'local' }}"
terrarium_zitadel_dir: "{{ terrarium_state_dir }}/zitadel"
terrarium_zitadel_postgres_dir: "{{ terrarium_zitadel_dir }}/postgres"
terrarium_zitadel_bootstrap_dir: "{{ terrarium_zitadel_dir }}/bootstrap"
terrarium_zitadel_outputs_path: /etc/terrarium/zitadel-apps.json
terrarium_zitadel_stage_dir: "{{ terrarium_state_dir }}/zitadel-container"
terrarium_zitadel_instance_name: terrarium-idp
terrarium_zitadel_instance_image: ubuntu:24.04
terrarium_zitadel_instance_profile: terrarium
terrarium_zitadel_api_port: 8082
terrarium_zitadel_login_port: 8083
terrarium_zitadel_version: v4.13.0
terrarium_docker_registry_config_path: /root/.docker/config.json
terrarium_docker_hardened_images: auto
terrarium_docker_hardened_image_mirrors: true
terrarium_zitadel_postgres_image: ""
terrarium_zitadel_postgres_image_hardened: "dhi.io/postgres:17.9-alpine3.22@sha256:53e316c761bfcaae02cdc6015c3a11a747fe9d0cde9cd0c3d4c871326862e7ed"
terrarium_zitadel_postgres_image_mirror: "ghcr.io/terion-name/terrarium-dhi-postgres:17.9-alpine3.22"
terrarium_zitadel_postgres_image_fallback: "postgres:17.9-alpine3.22@sha256:034839bd88128360cda25496ebdb1471e24a4aa09b937160c73df2bb51126308"
terrarium_zitadel_pat_expiration: "2099-01-01T00:00:00Z"
terrarium_zitadel_project_name: Terrarium
